MajiSafi/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from marketplace import views as MarketplaceViews
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name ='home'),
    path('', include('accounts.urls')),
    path('marketplace/', include('marketplace.urls')),

    # CART
    path('cart/', MarketplaceViews.CartListView.as_view(), name='cart'),

    #SEARCH
    path('search/', MarketplaceViews.SearchView.as_view(), name='search'),

    #CHECKOUT
    path('checkout/', MarketplaceViews.CheckoutView.as_view(), name='checkout'),

    #ORDERS
    path('orders/', include('orders.urls')),
    path('__debug__/', include(debug_toolbar.urls)),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('registerUser/',views.RegisterUserView.as_view(), name='registerUser'),
    path('registerSupplier/',views.RegisterSupplierView.as_view(), name='registerSupplier'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('myAccount/', views.MyAccountView.as_view(), name='myAccount'),
    path('customerDashboard/', views.CustomerDashboardView.as_view(), name='customerDashboard'),
    path('supplierDashboard/', views.SupplierDashboardView.as_view(), name='supplierDashboard'),

    path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),

    path('forgot_password/', views.ForgotPassword.as_view(), name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', views.ResetPasswordValidateView.as_view(), name='reset_password_validate'),
    path('reset_password/', views.ResetPasswordView.as_view(), name='reset_password'),
     path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),

    path('supplier/', include('supplier.urls')),
    path('customer/', include('customers.urls')),


]

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('place-order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
    path('order_complete/', views.OrderCompleteView.as_view(), name='order_complete'),

]

accounts/forms.py
from django import forms
from .models import User, UserProfile
from .validators import allow_only_images_valdators
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
import re

def validate_special_character(value):
    # This is a custom validator that adds aditional layer of complexity to ensure passwords
    # includes characters beyond alpha numeric ones
    pattern = r'[\W_]+'
    if not re.search(pattern, value):
        raise ValidationError('Password must contain at least one special character eg."~!@#$%^&*"')

class UserForm(forms.ModelForm):
    # validate_password ensures that the password meets Django's default password strength requirements
    password = forms.CharField(widget=forms.PasswordInput(), validators=[validate_password, validate_special_character])
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Passwords do not match!!')

        return confirm_password

    def clean_email(self):
        email = self.cleaned_data['email']
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            raise forms.ValidationError("Enter a valid email address.")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("A user with this email address already exists.")
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("A user with this username already exists.")
        return username

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}), validators=[allow_only_images_valdators])
    cover_photo = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}), validators=[allow_only_images_valdators])

    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'cover_photo', 'county', 'town', 'pin_code']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
        
        
class ChangePasswordForm(forms.Form):
    otp = forms.CharField(label='OTP')
    new_password = forms.CharField(widget=forms.PasswordInput(), label='New Password', validators=[validate_password, validate_special_character])
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label='Confirm New Password')

    def clean(self):
        # This method is called to clean and validate the form fields
        # It ensures all the fields are properly cleaned and validated before
        # custom logic is applied
        cleaned_data = super().clean() # Call the parent class's clean method to get the cleaned data
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password and confirm_password and new_password != confirm_password:
            raise ValidationError("New passwords do not match!")

        return cleaned_data
    

class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(), label='New Password', validators=[validate_password, validate_special_character])
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label='Confirm New Password')

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password and confirm_password and new_password != confirm_password:
            raise ValidationError("New passwords do not match!")
        
        return cleaned_data

accounts/views.py
import datetime
from django.utils.text import slugify
import random
from django.core.cache import cache
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from accounts.tasks import generate_qr_code_task
from supplier.forms import SupplierForm
from .forms import ChangePasswordForm, ResetPasswordForm, UserForm
from .models import User, UserProfile
from django.contrib import auth, messages
from django.contrib.auth import authenticate, login
from .utils import detectUser, send_email_verification, send_otp
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from supplier.models import Supplier
from django.template.defaultfilters import slugify
from orders.models import Order
from django.views.generic import View
from django.db import transaction
from .mixins import CustomerRoleRequiredMixin, SupplierRoleRequiredMixin
from django.views.generic.edit import FormView, CreateView
from django.views.generic import ListView


class RegisterUserView(CreateView):
    form_class = UserForm
    template_name = 'accounts/registerUser.html'
    success_url = reverse_lazy('registerUser')

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            messages.warning(self.request, 'You are already logged in')
            return redirect('myAccount')

        try:
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.role = User.CUSTOMER
            user.save()

            """
            send verification email to the registered user
            """
            subject = 'Account Activation'
            email_template = 'accounts/emails/account_email_verification.html'
            send_email_verification(
                self.request, user, subject, email_template
                )

            messages.success(
                self.request,
                "Your account has been created, an activation link has been sent to your email"
            )
            return super().form_valid(form)

        except Exception as e:
            print(f'Error during user registration: {e}')
            messages.error(self.request, "An error occurred during user registration. Please try again later.")


class RegisterSupplierView(View):
    def get(self, request):
        if request.user.is_authenticated:
            messages.warning(request, 'You are already logged in')
            return redirect('myAccount')
        form = UserForm()
        supplier_form = SupplierForm()
        context = {
            'form': form,
            'supplier_form': supplier_form,
        }
        return render(request, 'accounts/registerSupplier.html', context)

    def post(self, request):
        form = UserForm(request.POST)
        supplier_form = SupplierForm(request.POST, request.FILES)
        if form.is_valid() and supplier_form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            try:
                with transaction.atomic():
                    user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
                    user.role = User.WATER_SUPPLIER
                    user.save()
                    supplier = supplier_form.save(commit=False)
                    supplier.user = user
                    supplier_name = supplier_form.cleaned_data['supplier_name']
                    supplier.supplier_slug = slugify(supplier_name) + '-' + str(user.id)

                    """
                    Get the user profile from the UserProfile Model.
                    When the user.save is triggered,
                    Signals will create the user profile of the user
                    """

                    user_profile = UserProfile.objects.get(user=user)
                    supplier.user_profile = user_profile
                    supplier.save()
                    
                    # Trigger Celery task to generate QR code
                    generate_qr_code_task.delay(
                        supplier.id,
                        request.build_absolute_uri(f'/marketplace/{supplier.supplier_slug}/'),
                        supplier_name
                    )
                    
                    # Send Email Verification to the Registered Supplier
                    subject = 'Account Activation'
                    email_template = 'accounts/emails/account_email_verification.html'
                    send_email_verification(
                        request, user, subject, email_template
                    )

                    messages.success(request, "Your account has been created, an activation link has been sent to your email. Kindly wait for approval from the admin")
                    return redirect('registerSupplier')

            except Exception as e:
                print(f'An error occurred during supplier registration: {str(e)}')
                messages.error(request, f"An error occurred: {str(e)}. Please try again later.")
                return redirect('registerSupplier')
        else:
            messages.error(request, "Invalid form")
            return render(request, 'accounts/registerSupplier.html', {'form': form, 'supplier_form': supplier_form})


class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Your account has been activated')
        else:
            messages.error(request, 'Invalid activation link')

        return redirect('myAccount')


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            messages.warning(request, 'You are already logged in')
            return redirect('myAccount')
        return render(request, 'accounts/login.html')

    def post(self, request):
        if request.user.is_authenticated:
            messages.warning(request, 'You are already logged in')
            return redirect('myAccount')

        email = request.POST.get('email').strip().lower()
        password = request.POST.get('password')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'You are logged in')
            return redirect('myAccount')
        else:
            messages.error(request, 'Invalid Credentials')
            return redirect('login')


class LogoutView(View):
    def get(self, request):
        auth.logout(request)
        messages.info(request, "You have logged out")
        return redirect('login')


class MyAccountView(LoginRequiredMixin, View):
    """
    This view is responsible for detecting whether the User is a Customer or a Supplier and redirecting them to the respective dashboard.
    """
    login_url = 'login'

    def get(self, request, *args, **kwargs):
        user = request.user
        redirectUrl = detectUser(user)
        return redirect(redirectUrl)


class CustomerDashboardView(LoginRequiredMixin, CustomerRoleRequiredMixin, ListView):
    model = Order
    template_name = 'accounts/customerDashboard.html'
    context_object_name = 'recent_orders'
    login_url = 'login'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_ordered=True)[:6]
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders_count'] = self.get_queryset().count()
        return context


class SupplierDashboardView(LoginRequiredMixin, SupplierRoleRequiredMixin, View):
    login_url = 'login'

    def get(self, request, *args, **kwargs):
        supplier = Supplier.objects.get(user=request.user)
        orders = Order.objects.filter(suppliers__in=[supplier.id], is_ordered=True).order_by('-created_at')
        recent_orders = orders[:10]

        current_month = datetime.datetime.now().month
        current_month_orders = orders.filter(suppliers__in=[supplier.id], created_at__month=current_month)

        current_month_revenue = sum(i.get_total_by_supplier()['grand_total'] for i in current_month_orders)
        total_revenue = sum(i.get_total_by_supplier()['grand_total'] for i in orders)

        context = {
            'orders': orders,
            'orders_count': orders.count(),
            'recent_orders': recent_orders,
            'total_revenue': total_revenue,
            'current_month_revenue': current_month_revenue,
        }
        return render(request, 'accounts/supplierDashboard.html', context)


class ForgotPassword(View):
    def get(self, request):
        return render(request, 'accounts/forgot_password.html')

    def post(self, request):
        email = request.POST.get('email')

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            """
            Create a helper function for password reset email
            """

            subject = 'Password Reset'
            email_template = 'accounts/emails/reset_password_email.html'
            send_email_verification(request, user, subject, email_template)

            messages.success(
                request, 'Password reset link has been sent to your email address'
            )

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="width: 450px; min-height: auto;">
                        <div class="user-holder">
                            <h4 class="text-center" style="margin-bottom: 0;">Change Your Password</h4>
                            <hr>
                            <div id="restaurant-sets-holder">
                                <form action="{% url 'change_password' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% if form.non_field_errors %}
                                        <ul class="errorlist" style="color:red;">
                                            {% for error in form.non_field_errors %}
                                                <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label for="id_otp">OTP</label>
                                                                {{ form.otp }}
                                                                {% if form.otp.errors %}
                                                                    <ul class="errorlist" style="color:red;">
                                                                        {% for error in form.otp.errors %}
                                                                            <li>{{ error }}</li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label for="id_new_password">New Password</label>
                                                                {{ form.new_password }}
                                                                {% if form.new_password.errors %}
                                                                    <ul class="errorlist" style="color:red;">
                                                                        {% for error in form.new_password.errors %}
                                                                            <li>{{ error }}</li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label for="id_confirm_password">Confirm New Password</label>
                                                                {{ form.confirm_password }}
                                                                {% if form.confirm_password.errors %}
                                                                    <ul class="errorlist" style="color:red;">
                                                                        {% for error in form.confirm_password.errors %}
                                                                            <li>{{ error }}</li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <div class="payment-holder">
                                                            <input type="submit" value="Change Password" id="btn-next-restaurant-information" class="bgcolor">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <!-- Load message -->
                                                    {% include 'includes/alerts.html' %}
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome {{user.username}}</h1>

{% include 'includes/alerts.html' %}


{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="width: 450px; min-height: auto;">
                        <div class="user-holder">
                            <h4 class="text-center" style="margin-bottom: 0;">Change Your Password</h4>
                            <hr>
                            <div id="restaurant-sets-holder">
                                <form action="{% url 'reset_password' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% if form.non_field_errors %}
                                        <ul class="errorlist" style="color:red;">
                                            {% for error in form.non_field_errors %}
                                                <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label for="id_new_password">New Password</label>
                                                                {{ form.new_password }}
                                                                {% if form.new_password.errors %}
                                                                    <ul class="errorlist" style="color:red;">
                                                                        {% for error in form.new_password.errors %}
                                                                            <li>{{ error }}</li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label for="id_confirm_password">Confirm New Password</label>
                                                                {{ form.confirm_password }}
                                                                {% if form.confirm_password.errors %}
                                                                    <ul class="errorlist" style="color:red;">
                                                                        {% for error in form.confirm_password.errors %}
                                                                            <li>{{ error }}</li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <div class="payment-holder">
                                                            <input type="submit" value="Reset Password" id="btn-next-restaurant-information" class="bgcolor">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <!-- Load message -->
                                                    {% include 'includes/alerts.html' %}
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}